benchmark:
  base_dir: /home/yoon/workspace/repos/git_rky0930/MyTensorflowBenchmark
  image_dir: dataset/mscoco_val2017_via_format/mscoco_val2017/*
  max_example_num: 10000

accuracy:
  base_dir: /home/yoon/workspace/repos/git_rky0930/MyTensorflowBenchmark
  label_map: dataset/mscoco_val2017_via_format/mscoco_label_map.yaml
  annotation_file: dataset/mscoco_val2017_via_format/mscoco_val2017_region_data.json
  mode: ap # ap | map | raw_data
  iou_threshold: 0.1
  inference_result_file: mscoco_val2017_inference_result.json

object_detection:
  base_dir: /home/yoon/workspace/repos/git_rky0930/MyTensorflowBenchmark
  checkpoint: models/object_detection/tensorflow/ssd_mobilenet_v2_coco_2018_03_29/frozen_inference_graph.pb
  confidence_score_threshold: 0.5